# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_auto_20170327_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Powiat',
            new_name='Okreg',
        ),
        migrations.RenameField(
            model_name='gmina',
            old_name='powiat',
            new_name='okreg',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='powiat',
            new_name='okreg',
        ),
    ]
